# =============================================================================
# IMPORTS
# =============================================================================

# UI class generated by Qt Designer (from .ui file)
from second_ui import Ui_MainWindow

# Matplotlib for plotting FFT spectrum
from matplotlib.figure import Figure
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas

# Standard library imports
import sys
import os
import math
from pathlib import Path





# including ffmpeg for PyInstaller
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

# Check if we are running as a bundled app
if getattr(sys, 'frozen', False):
    # Point pydub to the bundled ffmpeg.exe
    from pydub import AudioSegment
    AudioSegment.converter = resource_path("ffmpeg.exe")



# Numerical and signal processing
import numpy as np
from scipy import signal

# PyQt6 GUI components
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog, QMessageBox, QLabel
from PyQt6.QtCore import Qt

# Audio handling loading, pitch shifting, saving
from pydub import AudioSegment
from mutagen import File as MutagenFile

# Force matplotlib to use QtAgg backend (compatible with PyQt6)
import matplotlib
matplotlib.use("QtAgg")

# =============================================================================
# CONSTANTS & HELPER FUNCTIONS
# =============================================================================

# Standard note names in order (C to B)
NOTE_NAMES = [
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"
]


def frequency_to_note(freq):
    """
    Convert a frequency in Hz to the closest musical note name and the
    deviation in semitones.

    Args:
        freq (float): Frequency in Hz (must be >0)

    Returns:
        tuple: (note_name, deviation_in_semitones)
                e.g. ("A4", 0.0) for 440 Hz
    """
    if freq <= 0 or np.isnan(freq) or np.isinf(freq):
        return ("?", 0.0)
    # MIDI note number: 69 = A4 (440 Hz)
    midi = 69 + 12 * math.log2(freq / 440.0)
    midi_rounded = int(round(midi))
    semitone = midi_rounded % 12
    octave = midi_rounded // 12 - 1
    note = f"{NOTE_NAMES[semitone]}{octave}"
    return (note, midi - midi_rounded)


def frequency_to_semitones(original_freq, target_freq):
    """
    Calculate the number of semitones needed to shift original_freq to target_freq.

    Args:
        original_freq, target_freq (float): frequencies in Hz

    Returns:
        float: semitone shift (positive = pitch up)
    """
    return 12 * np.log2(target_freq / original_freq)


def change_pitch_pydub_segment(audio_segment, semitones):
    """
    Change the pitch of a pydub AudioSegment without changing its duration.
    Uses resampling trick: change sample rate, then resample back.

    Args:
        audio_segment (pydub.AudioSegment): input audio
        semitones (float): number of semitones to shift (+ = up)

    Returns:
        pydub.AudioSegment: pitch-shifted audio (same duration, same sample rate)
    """
    new_sample_rate = int(audio_segment.frame_rate * (2 ** (semitones / 12.0)))
    # Spawn with overridden frame_rate (raw data unchanged)
    pitched = audio_segment._spawn(audio_segment.raw_data, overrides={
                                   'frame_rate': new_sample_rate})
    # Resample back to original frame rate to keep duration unchanged
    pitched = pitched.set_frame_rate(audio_segment.frame_rate)
    return pitched

# =============================================================================
# CUSTOM DROP LABEL (Drag & Drop + Click to Browse)
# =============================================================================


class FileDropLabel(QLabel):
    """A QLabel that accepts file drops and opens file dialog on click."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setText("🎵 Drag audio here\nor click to browse")
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setStyleSheet("""
            QLabel {
                background-color: #82E2FF;
                border: 5px solid #ccc;
                font-family: Arial, sans-serif;
                font-size: 16px;
                color: #333;
                border-radius: 10px;
            }
            QLabel:hover {
                background-color: #e9ecef;
                border-color: #999;
            }
        """)
        self.setAcceptDrops(True)      # Enable drag events
        self.on_files_callback = None  # Will be set by MainWindow

    def set_on_files_callback(self, callback):
        """Register a function to call when files are dropped/selected."""
        self.on_files_callback = callback

    def mousePressEvent(self, event):
        """Handle click: open file dialog."""
        path, _ = QFileDialog.getOpenFileName(self, "Select audio file",
                                              filter="Audio Files (*.mp3 *.wav *.flac *.ogg);;All Files (*)")
        if path and self.on_files_callback:
            self.on_files_callback([path])

    def dragEnterEvent(self, event):
        """Change style when drag enters to indicate valid drop target."""
        if event.mimeData().hasUrls():
            event.acceptProposedAction()
            self.setStyleSheet("""
                QLabel {
                    background-color: #b2dfdb;
                    border: 5px solid #4CAF50;
                    font-family: Arial, sans-serif;
                    font-size: 16px;
                    color: #333;
                    border-radius: 10px;
                }
            """)
        else:
            event.ignore()

    def dragLeaveEvent(self, event):
        """Revert style when drag leaves."""
        self.setStyleSheet("""
            QLabel {
                background-color: #82E2FF;
                border: 5px solid #ccc;
                font-family: Arial, sans-serif;
                font-size: 16px;
                color: #333;
                border-radius: 10px;
            }
            QLabel:hover {
                background-color: #e9ecef;
                border-color: #999;
            }
        """)

    def dropEvent(self, event):
        """Handle drop event: extract local file paths and call callback."""
        urls = event.mimeData().urls()
        paths = [u.toLocalFile() for u in urls if u.isLocalFile()]
        if paths and self.on_files_callback:
            self.on_files_callback(paths)
        # Provide visual feedback
        self.setStyleSheet("""
            QLabel {
                background-color: #90caf9;
                border: 5px solid #2196F3;
                font-family: Arial, sans-serif;
                font-size: 16px;
                color: #333;
                border-radius: 10px;
            }
            QLabel:hover {
                background-color: #e9ecef;
                border-color: #999;
            }
        """)
        event.acceptProposedAction()

# =============================================================================
# METADATA EXTRACTION (using mutagen)
# =============================================================================


def extract_metadata(path):
    """Extract title, artist, album, duration from audio file using mutagen."""
    meta = {"title": None, "artist": None, "album": None, "duration": None}
    try:
        m = MutagenFile(path, easy=True)
        if m is not None:
            meta["duration"] = getattr(m.info, "length", None)
            meta["title"] = (m.get("title") or [None])[0]
            meta["artist"] = (m.get("artist") or [None])[0]
            meta["album"] = (m.get("album") or [None])[0]
    except Exception:
        pass  # Silently ignore metadata errors (not critical)
    return meta

# =============================================================================
# CUSTOM MATPLOTLIB CANVAS FOR FFT DISPLAY
# =============================================================================


class FFTCanvas(FigureCanvas):
    """Matplotlib canvas embedded in Qt, dedicated to FFT spectrum plot."""

    def __init__(self, parent=None, width=6, height=3.5, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.ax = fig.add_subplot(111)   # single subplot
        super().__init__(fig)
        self.setParent(parent)
        fig.tight_layout()

# =============================================================================
# MAIN WINDOW (inherits from both QMainWindow and the generated UI class)
# =============================================================================


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)   # builds UI from second_ui

        # ---------- State variables ----------
        self.loaded_path = None       # path of the loaded audio file
        self.loaded_segment = None    # pydub AudioSegment object
        self.sample_rate = None       # sample rate in Hz
        self.y_mono = None            # mono float array (normalized [-1,1])
        self.duration_s = None        # duration in seconds

        # ---------- Replace existing QLabel with custom FileDropLabel ----------
        parent_widget = self.label.parent()
        layout = parent_widget.layout()
        layout.removeWidget(self.label)
        self.label.deleteLater()      # remove the original label from .ui

        self.drop_label = FileDropLabel(parent_widget)
        self.drop_label.setMinimumSize(350, 220)
        self.drop_label.set_on_files_callback(self.handle_files)
        layout.addWidget(self.drop_label, 1, 1, 1, 1)

        # ---------- FFT canvas (placed manually because design is fixed) ----------
        self.fft_canvas = FFTCanvas(
            self.p2_setting, width=4.9, height=1.8, dpi=100)
        self.fft_canvas.setGeometry(40, 400, 520, 230)   # absolute positioning
        self.fft_canvas.ax.set_title("FFT / Spectral Peak")
        # Connect mouse events for zoom/pan
        self.fft_canvas.mpl_connect("scroll_event", self._on_scroll)
        self.fft_canvas.mpl_connect("button_press_event", self._on_click)

        # ---------- Speed slider (0..1000 maps to 0.25x..2.0x) ----------
        self.horizontalSlider_2_speed.setMinimum(0)
        self.horizontalSlider_2_speed.setMaximum(1000)
        self.horizontalSlider_2_speed.setValue(500)  # default value
        self.horizontalSlider_2_speed.valueChanged.connect(
            self.on_speed_changed)

        # ---------- Button connections ----------
        self.btn_2_done.clicked.connect(self.on_done_clicked)
        self.btn_3_yes.clicked.connect(self.on_confirm_yes)
        self.btn_3_no.clicked.connect(self.on_confirm_no)

        # Make result text boxes read-only
        self.plainTextEdit_2_results.setReadOnly(True)
        self.plainTextEdit_3_results.setReadOnly(True)
        self.plainTextEdit_4_final.setReadOnly(True)

        # Default combobox selections (these are filled by UI designer)
        self.comboBox_2_from.setCurrentIndex(0)
        self.comboBox_2_to.setCurrentIndex(0)
        self.comboBox_2_format.setCurrentIndex(0)
        self.output_file_path = None

    # -------------------------------------------------------------------------
    # File handling
    # -------------------------------------------------------------------------
    def handle_files(self, paths):
        """Callback from FileDropLabel: loads the first file."""
        if paths:
            self.load_audio_file(paths[0])

    def load_audio_file(self, path):
        """
        Load audio file using pydub, convert to mono numpy array,
        compute basic analysis, and switch to page 2 (analysis page).
        """
        if not os.path.isfile(path):
            QMessageBox.warning(self, "File error",
                                "Selected path is not a file.")
            return

        # Visual feedback during loading
        self.drop_label.setText("🔄 Loading audio file...")
        self.drop_label.setStyleSheet("""
            QLabel {
                background-color: #e3f2fd;
                border: 5px solid #2196F3;
                padding: 20px;
                font-family: Arial, sans-serif;
                font-size: 16px;
                color: #333;
                border-radius: 10px;
            }
        """)

        QtWidgets.QApplication.processEvents()  # forcing UI update

        # Attempting to load with pydub (requires ffmpeg)
        try:
            seg = AudioSegment.from_file(path)
        except Exception as e:
            self.drop_label.setText("🎵 Drag audio here\nor click to browse")
            QMessageBox.critical(self, "Load error",
                                 f"Could not load the file. Make sure ffmpeg is installed.\nError: {e}")
            return

        # Store data
        self.loaded_path = path
        self.loaded_segment = seg
        self.sample_rate = seg.frame_rate
        self.duration_s = len(seg) / 1000.0

        # Convert to mono float numpy array [-1, 1]
        samples = seg.get_array_of_samples()
        arr = np.array(samples).astype(np.float32)
        channels = seg.channels
        if channels > 1:
            arr = arr.reshape((-1, channels))
            arr = arr.mean(axis=1)          # average to mono
        # Normalize based on sample width (e.g., 16-bit -> max 32768)
        sample_width = seg.sample_width
        max_val = float(1 << (8 * sample_width - 1))
        y = arr / max_val
        self.y_mono = y

        # Updating UI to show loaded file name
        file_name = os.path.basename(path)
        self.drop_label.setText(
            f"✅ Loaded: {file_name}\n🎵 Drag another or click to browse")
        # Changing style to success...
        self.update_page2_analysis()
        self.stackedWidget.setCurrentIndex(1)   # go to analysis page

    # -------------------------------------------------------------------------
    # Analysis page: compute spectral features and display FFT
    # -------------------------------------------------------------------------
    def update_page2_analysis(self):
        """Compute RMS, peak, zero-crossing, FFT, dominant frequency, and plot."""
        y = self.y_mono
        sr = self.sample_rate
        if y is None:
            return

        # Time-domain stats
        rms = np.sqrt(np.mean(y**2))
        peak = np.max(np.abs(y))
        # Zero-crossing rate: average number of sign changes per sample
        zc = np.mean(np.abs(np.diff(np.sign(y)))) / 2.0

        # FFT
        n = len(y)
        freqs = np.fft.rfftfreq(n, d=1.0/sr)
        fft_mag = np.abs(np.fft.rfft(y))

        # Smooth magnitude spectrum with Savitzky-Golay filter to reduce noise
        window_len = 101 if len(fft_mag) > 101 else (
            len(fft_mag)-1 if (len(fft_mag)-1) % 2 == 1 else len(fft_mag)-2)
        if window_len >= 5:
            try:
                fft_mag_smooth = signal.savgol_filter(fft_mag, window_len, 3)
            except Exception:
                fft_mag_smooth = fft_mag
        else:
            fft_mag_smooth = fft_mag

        # Peak detection (find local maxima)
        peaks, props = signal.find_peaks(fft_mag_smooth,
                                         height=np.max(fft_mag_smooth)*0.1,
                                         distance=20)
        peak_freqs = freqs[peaks] if len(peaks) > 0 else np.array([])
        peak_mags = fft_mag_smooth[peaks] if len(peaks) > 0 else np.array([])

        # Dominant frequency/note (highest peak)
        if len(peak_freqs) > 0:
            idx_top = np.argmax(peak_mags)
            dom_freq = float(peak_freqs[idx_top])
            dom_note, _ = frequency_to_note(dom_freq)
        else:
            dom_freq = 0.0
            dom_note = "?"

        # Build text report
        lines = []
        lines.append(f"File: {os.path.basename(self.loaded_path)}")
        lines.append(f"Sample rate: {sr} Hz")
        lines.append(f"Duration: {self.duration_s:.2f} s")
        lines.append(f"RMS: {rms:.6f}")
        lines.append(f"Peak amplitude: {peak:.6f}")
        lines.append(f"Zero-crossing (approx): {zc:.6f}")
        lines.append(f"Dominant freq: {dom_freq:.2f} Hz -> {dom_note}")
        lines.append("")
        lines.append("Top spectral peaks (freq Hz -> note):")
        for f in peak_freqs[:8]:
            note, _ = frequency_to_note(f)
            lines.append(f"  {f:.1f} Hz -> {note}")
        self.plainTextEdit_2_results.setPlainText("\n".join(lines))

        # Plot FFT with annotations for top peaks
        ax = self.fft_canvas.ax
        ax.clear()
        ax.plot(freqs, fft_mag_smooth, color="tab:blue")
        ax.set_xlabel("Frequency (Hz)")
        ax.set_ylabel("Magnitude")
        ax.set_xscale("log")                    # log frequency axis
        ax.set_xlim(20, sr/2 if sr/2 > 20 else 1000)
        for f, m in zip(peak_freqs[:10], peak_mags[:10]):
            note, _ = frequency_to_note(f)
            ax.annotate(f"{note}\n{f:.1f}Hz", xy=(f, m), xytext=(0, 5),
                        textcoords="offset points", ha="center", fontsize=8, rotation=45)
        self.fft_canvas.draw()

    # -------------------------------------------------------------------------
    # FFT canvas interactivity: scroll to zoom, double-click to reset
    # -------------------------------------------------------------------------
    def _on_scroll(self, event):
        """Zoom in/out on the FFT plot using mouse wheel."""
        ax = self.fft_canvas.ax
        x_min, x_max = ax.get_xlim()
        xdata = event.xdata if event.xdata is not None else (x_min + x_max) / 2
        # step < 0 = scroll down (zoom out)
        scale_factor = 1.2 if event.step < 0 else 0.8
        new_width = (x_max - x_min) * scale_factor
        left = xdata - (xdata - x_min) * scale_factor
        right = left + new_width
        # Clamp to valid frequency range
        left = max(1, left)
        right = min(self.sample_rate/2, right)
        ax.set_xlim(left, right)
        self.fft_canvas.draw()

    def _on_click(self, event):
        """Double-click resets x-axis to full range [20 Hz, Nyquist]."""
        if event.dblclick:
            ax = self.fft_canvas.ax
            ax.set_xlim(20, self.sample_rate/2)
            self.fft_canvas.draw()

    # -------------------------------------------------------------------------
    # Speed slider callback
    # -------------------------------------------------------------------------
    def on_speed_changed(self, value):
        """
        Convert slider value (0-1000) to speed multiplier between 0.25 and 2.0.
        Also update the speed label.
        """
        t = value / 1000.0                 # 0..1
        mult = 0.25 + (2.0 - 0.25) * t     # linear interpolation
        self.lbl_2_speed.setText(f"speed  X {mult:.3f}")
        return mult

    # -------------------------------------------------------------------------
    # Page 2 -> Page 3 (confirmation summary)
    # -------------------------------------------------------------------------
    def on_done_clicked(self):
        """User finished adjusting parameters; show transformation summary."""
        if self.loaded_path is None:
            QMessageBox.warning(self, "No file", "Please upload a file first.")
            return
        from_text = self.comboBox_2_from.currentText()
        to_text = self.comboBox_2_to.currentText()
        fmt = self.comboBox_2_format.currentText().strip()
        speed_mult = self.on_speed_changed(
            self.horizontalSlider_2_speed.value())

        summary_lines = []
        summary_lines.append(
            f"Original file: {os.path.basename(self.loaded_path)}")
        summary_lines.append(f"From: {from_text}")
        summary_lines.append(f"To: {to_text}")
        summary_lines.append(f"Speed multiplier: {speed_mult:.3f}x")
        summary_lines.append(f"Output format: {fmt}")
        summary_lines.append("")
        summary_lines.append("Effects to be applied if you confirm:")
        summary_lines.append(
            " - Pitch shift from selected 'from' to 'to' (semitone conversion)")
        summary_lines.append(" - Speed change by multiplier")
        summary_lines.append(" - Save in selected format")
        self.plainTextEdit_3_results.setPlainText("\n".join(summary_lines))
        self.stackedWidget.setCurrentIndex(2)   # go to confirmation page

    # -------------------------------------------------------------------------
    # Confirmation page: No = reset and go back to adjustment page
    # -------------------------------------------------------------------------
    def on_confirm_no(self):
        """Reset all controls to default and go back to page 2."""
        self.horizontalSlider_2_speed.setValue(500)
        self.comboBox_2_from.setCurrentIndex(0)
        self.comboBox_2_to.setCurrentIndex(0)
        self.comboBox_2_format.setCurrentIndex(0)
        self.plainTextEdit_3_results.clear()
        self.stackedWidget.setCurrentIndex(1)

    # -------------------------------------------------------------------------
    # Yes = perform transformations and save file
    # -------------------------------------------------------------------------
    def on_confirm_yes(self):
        """Apply pitch shift and speed change, then save the file."""
        try:
            out_path = self.apply_transformations_and_save()
        except Exception as e:
            QMessageBox.critical(self, "Processing error",
                                 f"Error during processing: {e}")
            return
        self.output_file_path = out_path
        basename = os.path.basename(out_path)
        folder = os.path.dirname(out_path)
        self.plainTextEdit_4_final.setPlainText(
            f"Saved file:\n{basename}\n\nFolder:\n{folder}")
        self.stackedWidget.setCurrentIndex(3)   # final page

    # -------------------------------------------------------------------------
    # Core audio processing: pitch shift + time stretch (speed)
    # -------------------------------------------------------------------------
    def apply_transformations_and_save(self):
        """
        - Parse 'From' and 'To' frequencies from combobox text
        - Compute semitone shift
        - Apply pitch shift using pydub method
        - Apply speed change (time stretch) by resampling
        - Export to chosen format
        - Return path of saved file
        """
        fmt = self.comboBox_2_format.currentText().strip().lower()
        from_text = self.comboBox_2_from.currentText()
        to_text = self.comboBox_2_to.currentText()

        # Extract numeric frequency from strings like "A4 (440 Hz)"
        def parse_freq(s):
            if "(" in s and ")" in s:
                inside = s.split("(")[1].split(")")[0]
                if "Hz" in inside:
                    return float(inside.replace("Hz", "").strip())
            try:
                return float(s)
            except:
                return None

        orig_freq = parse_freq(from_text)
        target_freq = parse_freq(to_text)
        if orig_freq is None or target_freq is None:
            raise RuntimeError("Could not parse frequencies from selections.")

        semitones = frequency_to_semitones(orig_freq, target_freq)
        speed_mult = self.on_speed_changed(
            self.horizontalSlider_2_speed.value())

        seg = self.loaded_segment
        # 1. Pitch shift (preserves duration)
        seg = change_pitch_pydub_segment(seg, semitones)

        # 2. Speed change (time stretch) by changing frame_rate and resampling
        new_frame_rate = int(seg.frame_rate * speed_mult)
        sped = seg._spawn(seg.raw_data, overrides={
                          'frame_rate': new_frame_rate})
        # restore original sample rate
        sped = sped.set_frame_rate(seg.frame_rate)
        final = sped

        # Build output filename with all parameters
        orig_name = Path(self.loaded_path).stem
        ext_map = {"mp3": "mp3", "wav": "wav", "flac": "flac", "ogg": "ogg"}
        fmt_key = fmt.lower().strip()
        out_ext = ext_map.get(fmt_key, "mp3")
        from_label = from_text.split("(")[0].strip().replace(" ", "")
        to_label = to_text.split("(")[0].strip().replace(" ", "")
        speed_val = self.on_speed_changed(
            self.horizontalSlider_2_speed.value())
        out_name_base = f"{orig_name}_from-{from_label}_to-{to_label}_speed-{speed_val:.3f}_format-{out_ext}"
        out_dir = os.getcwd()
        out_name = f"{out_name_base}.{out_ext}"
        out_path = os.path.join(out_dir, out_name)

        # Avoid overwriting the original name: add _1, _2, etc.
        counter = 1
        base_candidate = out_path
        while os.path.exists(base_candidate):
            base_candidate = os.path.join(
                out_dir, f"{out_name_base}_{counter}.{out_ext}")
            counter += 1
        out_path = base_candidate

        final.export(out_path, format=out_ext)
        return out_path

# =============================================================================
# APPLICATION ENTRY POINT
# =============================================================================


def main():
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
